# Uses official Cypress docker image for dependencies
# https://docs.cypress.io/guides/continuous-integration/introduction#Official-Cypress-Docker-Images
image: node:20.11.0

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - node
        script:
          - npm install
          - npm run build
          - npm run test
        artifacts:
          - .next/**

    - step:
        name: API Tests
        image: justb4/soapui:latest
        script:
          # Start the Next.js application
          - npm install
          - npm run build
          - npm run start &
          - sleep 10 # Wait for the app to start

          # Run SoapUI tests
          - soapui-testrunner.sh -j -f test-reports -r -a insurance-api-tests.xml
        artifacts:
          - test-reports/**

  branches:
    main:
      - step:
          name: Build and Test
          caches:
            - node
          script:
            - npm install
            - npm run build
            - npm run test
          artifacts:
            - .next/**

      - step:
          name: API Tests
          image: justb4/soapui:latest
          script:
            # Start the Next.js application
            - npm install
            - npm run build
            - npm run start &
            - sleep 10 # Wait for the app to start

            # Run SoapUI tests
            - soapui-testrunner.sh -j -f test-reports -r -a Rating-API-soapui-project.xml
          artifacts:
            - test-reports/**

definitions:
  caches:
    node: node_modules
