# Uses official Cypress docker image for dependencies
# https://docs.cypress.io/guides/continuous-integration/introduction#Official-Cypress-Docker-Images
image: cypress/base:20.9.0

pipelines:
  default:
    - step:
        name: Install and Build
        caches:
          - npm
          - cypress
          - node
        script:
          - npm ci --prefer-offline
          - npm run build
        artifacts:
          - my-app/.next/**
    - parallel:
        - step:
            name: Cypress Tests
            caches:
              - npm
              - cypress
              - node
            script:
              - npm ci --prefer-offline
              - npm run build
              - npm start &
              - npx wait-on 'http-get://localhost:3000'
              - npx cypress run
definitions:
  caches:
    npm: $HOME/.npm
    cypress: $HOME/.cache/Cypress
