# Uses official Cypress docker image for dependencies
# https://docs.cypress.io/guides/continuous-integration/introduction#Official-Cypress-Docker-Images
image: node:20.11.0

pipelines:
  default:
    - step:
        name: Build and Test...
        caches:
          - node
          - cypress
        script:
          # Install dependencies
          - npm install
          - npm run build

          # Run Jest tests
          - npm run test

          # Start app and run Cypress tests
          - npm run start &
          - sleep 10
          - npx cypress run
        artifacts:
          - .next/**
          - cypress/videos/**
          - cypress/screenshots/**

    - step:
        name: Run SoapUI Tests...
        script:
          # Install dependencies
          - apt-get update && apt-get install -y wget unzip

          # Download and setup SoapUI
          - wget https://s3.amazonaws.com/downloads.eviware/soapuios/5.6.0/SoapUI-5.6.0-linux-bin.tar.gz
          - tar -xzf SoapUI-5.6.0-linux-bin.tar.gz
          - cd SoapUI-5.6.0

          # Start the Next.js application
          - npm install
          - npm run build
          - npm run start &
          - sleep 10 # Wait for the app to start

          # Run SoapUI tests
          - bin/testrunner.sh -j -f /tmp/soapui-results -r -a -s "TestSuite" Rating-API-soapui-project.xml
        artifacts:
          - /tmp/soapui-results/**

definitions:
  caches:
    node: node_modules
    cypress: ~/.cache/Cypress
